### ISSUE TITLE
'jill install' - Windows: The system cannot find the file specified

### ISSUE THREAD

**Issue by Laxzal** [johnnychen94/jill.py#122] opened 2022-12-31 09:28 UTC
Hi, when attempting to install julia through jill, I receive the following error:

![image](https://user-images.githubusercontent.com/56573970/210131769-8f3d14ea-1c0b-4eff-a6fb-a46a9e926ca5.png)

I attempted both ways - python and mambaforge prompt but receive the same error

**Comment by johnnychen94** [comment] 2023-03-19 06:56
I cannot reproduce this

```powershell
PS C:\Users\jc> jill install 1.9.0-rc1
JILL - Julia Installer 4 Linux (MacOS, Windows and FreeBSD) -- Light

jill will:
  1) install Julia 1.9.0-rc1 for winnt-x86_64 into C:\Users\jc\AppData\Local\julias
  2) make symlinks in C:\Users\jc\AppData\Local\julias\bin
You may need to manually add C:\Users\jc\AppData\Local\julias\bin to PATH
Continue installation? [Y/n]
----- Download Julia -----
downloading Julia release for 1.9.0-rc1-winnt-x86_64
downloading from https://mirrors.ustc.edu.cn/julia-releases/bin/winnt/x64/1.9/julia-1.9.0-rc1-win64.exe
100% [........................................................................] 94313496 / 94313496
finished downloading julia-1.9.0-rc1-win64.exe
----- Install Julia -----
install Julia to C:\Users\jc\AppData\Local\julias\julia-1.9
add C:\Users\jc\AppData\Local\julias\bin to PATH

SUCCESS: Specified value was saved.
you need to restart your current shell to update PATH
make new symlink C:\Users\jc\AppData\Local\julias\bin\julia-1.9.cmd
----- Post Installation -----
remove downloaded files...
remove C:\Users\jc\julia-1.9.0-rc1-win64.exe
Done!
```

Without much useful information on what could probably go wrong, I'm closing this issue. But feel free to add more details and I'll reopen it.

**Closed by johnnychen94** 2023-03-19 06:56 UTC
